/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package logindemo;


import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


/**
 *
 * @author Raymond
 */
public class UserCatalog extends javax.swing.JFrame {
    Connection con = null;
    String Query= "";
    int UserID, transID, quantity, price;
    Statement stmt;
    java.sql.Timestamp date = new java.sql.Timestamp(new java.util.Date().getTime());
    /**
     * Creates new form UserCatalog
     */
    public UserCatalog() {
        initComponents();
        javaconnect.connectdb();
        this.setLocationRelativeTo(null);
    }
    
    public UserCatalog(int pass) throws SQLException {
        initComponents();
        javaconnect.connectdb();
        this.UserID = pass;
        getFirstName(UserID);
        this.setLocationRelativeTo(null);
    }

    public void getFirstName (int u) throws SQLException {
        Connection nameCon = javaconnect.connectdb();
        try (PreparedStatement ps = nameCon.prepareStatement("select FIRST_NAME from LOGINTABLE where USER_ID=?")){
            ps.setInt(1, u);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next()) {
                    currUser.setText(rs.getString("FIRST_NAME") + "!");
                }
            }
        }
        nameCon.close();
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        motherPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mainKa = new javax.swing.JPanel();
        heading = new javax.swing.JLabel();
        prod1 = new javax.swing.JPanel();
        prodName1 = new javax.swing.JLabel();
        pic1 = new javax.swing.JLabel();
        sellPrice1 = new javax.swing.JLabel();
        pesoSign1 = new javax.swing.JLabel();
        quanLabel1 = new javax.swing.JLabel();
        qtyNum1 = new javax.swing.JTextField();
        prodCheck1 = new javax.swing.JCheckBox();
        prod2 = new javax.swing.JPanel();
        prodName2 = new javax.swing.JLabel();
        pic2 = new javax.swing.JLabel();
        sellPrice2 = new javax.swing.JLabel();
        pesoSign2 = new javax.swing.JLabel();
        quanLabel2 = new javax.swing.JLabel();
        qtyNum2 = new javax.swing.JTextField();
        prodCheck2 = new javax.swing.JCheckBox();
        prod3 = new javax.swing.JPanel();
        prodName3 = new javax.swing.JLabel();
        pic3 = new javax.swing.JLabel();
        sellPrice3 = new javax.swing.JLabel();
        pesoSign3 = new javax.swing.JLabel();
        quanLabel3 = new javax.swing.JLabel();
        qtyNum3 = new javax.swing.JTextField();
        prodCheck3 = new javax.swing.JCheckBox();
        prod4 = new javax.swing.JPanel();
        prodName4 = new javax.swing.JLabel();
        pic4 = new javax.swing.JLabel();
        sellPrice4 = new javax.swing.JLabel();
        pesoSign4 = new javax.swing.JLabel();
        quanLabel4 = new javax.swing.JLabel();
        qtyNum4 = new javax.swing.JTextField();
        prodCheck4 = new javax.swing.JCheckBox();
        prod5 = new javax.swing.JPanel();
        prodName5 = new javax.swing.JLabel();
        pic5 = new javax.swing.JLabel();
        sellPrice5 = new javax.swing.JLabel();
        pesoSign5 = new javax.swing.JLabel();
        quanLabel5 = new javax.swing.JLabel();
        qtyNum5 = new javax.swing.JTextField();
        prodCheck5 = new javax.swing.JCheckBox();
        prod6 = new javax.swing.JPanel();
        prodName6 = new javax.swing.JLabel();
        pic6 = new javax.swing.JLabel();
        sellPrice6 = new javax.swing.JLabel();
        pesoSign6 = new javax.swing.JLabel();
        quanLabel6 = new javax.swing.JLabel();
        qtyNum6 = new javax.swing.JTextField();
        prodCheck6 = new javax.swing.JCheckBox();
        prod7 = new javax.swing.JPanel();
        prodName7 = new javax.swing.JLabel();
        pic7 = new javax.swing.JLabel();
        sellPrice7 = new javax.swing.JLabel();
        pesoSign7 = new javax.swing.JLabel();
        quanLabel7 = new javax.swing.JLabel();
        qtyNum7 = new javax.swing.JTextField();
        prodCheck7 = new javax.swing.JCheckBox();
        prod8 = new javax.swing.JPanel();
        prodName8 = new javax.swing.JLabel();
        pic8 = new javax.swing.JLabel();
        sellPrice8 = new javax.swing.JLabel();
        pesoSign8 = new javax.swing.JLabel();
        quanLabel8 = new javax.swing.JLabel();
        qtyNum8 = new javax.swing.JTextField();
        prodCheck8 = new javax.swing.JCheckBox();
        prod9 = new javax.swing.JPanel();
        prodName9 = new javax.swing.JLabel();
        pic9 = new javax.swing.JLabel();
        sellPrice9 = new javax.swing.JLabel();
        pesoSign9 = new javax.swing.JLabel();
        quanLabel9 = new javax.swing.JLabel();
        qtyNum9 = new javax.swing.JTextField();
        prodCheck9 = new javax.swing.JCheckBox();
        checkoutBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        currUser = new javax.swing.JLabel();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(240, 142, 142));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(811, 632));
        setResizable(false);

        motherPanel.setBackground(new java.awt.Color(240, 142, 142));

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setPreferredSize(new java.awt.Dimension(1020, 1300));

        mainKa.setBackground(new java.awt.Color(255, 153, 153));
        mainKa.setForeground(new java.awt.Color(255, 255, 255));
        mainKa.setPreferredSize(new java.awt.Dimension(997, 1300));

        heading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logindemo/allproducts.PNG"))); // NOI18N

        prod1.setBackground(new java.awt.Color(255, 255, 255));
        prod1.setPreferredSize(new java.awt.Dimension(230, 230));

        prodName1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        prodName1.setText("Apieu Sheet Mask");

        pic1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logindemo/apieu mask1.jpg"))); // NOI18N
        pic1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        sellPrice1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sellPrice1.setText("100.00");

        pesoSign1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pesoSign1.setText("₱");

        quanLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        quanLabel1.setText("Quantity:");

        qtyNum1.setText("1");

        prodCheck1.setBackground(new java.awt.Color(255, 255, 255));
        prodCheck1.setText("Add to Cart");
        prodCheck1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodCheck1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout prod1Layout = new javax.swing.GroupLayout(prod1);
        prod1.setLayout(prod1Layout);
        prod1Layout.setHorizontalGroup(
            prod1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prod1Layout.createSequentialGroup()
                .addGroup(prod1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(prod1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pic1))
                    .addGroup(prod1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(prodName1))
                    .addGroup(prod1Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(pesoSign1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sellPrice1))
                    .addGroup(prod1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(prod1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(prodCheck1)
                            .addGroup(prod1Layout.createSequentialGroup()
                                .addComponent(quanLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(qtyNum1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        prod1Layout.setVerticalGroup(
            prod1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, prod1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pic1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(prod1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesoSign1)
                    .addComponent(sellPrice1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(prod1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtyNum1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quanLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(prodCheck1)
                .addContainerGap())
        );

        prod2.setBackground(new java.awt.Color(255, 255, 255));
        prod2.setPreferredSize(new java.awt.Dimension(230, 230));

        prodName2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        prodName2.setText("Apieu Milk Mask");

        pic2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logindemo/apieu2 mask1.jpg"))); // NOI18N
        pic2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        sellPrice2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sellPrice2.setText("150.00");

        pesoSign2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pesoSign2.setText("₱");

        quanLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        quanLabel2.setText("Quantity:");

        qtyNum2.setText("1");
        qtyNum2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyNum2ActionPerformed(evt);
            }
        });

        prodCheck2.setBackground(new java.awt.Color(255, 255, 255));
        prodCheck2.setText("Add to Cart");

        javax.swing.GroupLayout prod2Layout = new javax.swing.GroupLayout(prod2);
        prod2.setLayout(prod2Layout);
        prod2Layout.setHorizontalGroup(
            prod2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prod2Layout.createSequentialGroup()
                .addGroup(prod2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(prod2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pic2))
                    .addGroup(prod2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(prodName2))
                    .addGroup(prod2Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(pesoSign2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sellPrice2))
                    .addGroup(prod2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(prod2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(prodCheck2)
                            .addGroup(prod2Layout.createSequentialGroup()
                                .addComponent(quanLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(qtyNum2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        prod2Layout.setVerticalGroup(
            prod2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, prod2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pic2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodName2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(prod2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesoSign2)
                    .addComponent(sellPrice2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(prod2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtyNum2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quanLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(prodCheck2)
                .addContainerGap())
        );

        prod3.setBackground(new java.awt.Color(255, 255, 255));
        prod3.setPreferredSize(new java.awt.Dimension(230, 230));

        prodName3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        prodName3.setText("Aztec Face Mask");

        pic3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logindemo/aztec facemask.jpg"))); // NOI18N
        pic3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        sellPrice3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sellPrice3.setText("209.00");

        pesoSign3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pesoSign3.setText("₱");

        quanLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        quanLabel3.setText("Quantity:");

        qtyNum3.setText("1");

        prodCheck3.setBackground(new java.awt.Color(255, 255, 255));
        prodCheck3.setText("Add to Cart");

        javax.swing.GroupLayout prod3Layout = new javax.swing.GroupLayout(prod3);
        prod3.setLayout(prod3Layout);
        prod3Layout.setHorizontalGroup(
            prod3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prod3Layout.createSequentialGroup()
                .addGroup(prod3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(prod3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pic3))
                    .addGroup(prod3Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(pesoSign3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sellPrice3))
                    .addGroup(prod3Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(prod3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(prodCheck3)
                            .addGroup(prod3Layout.createSequentialGroup()
                                .addComponent(quanLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(qtyNum3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(prod3Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(prodName3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        prod3Layout.setVerticalGroup(
            prod3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, prod3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pic3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodName3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(prod3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesoSign3)
                    .addComponent(sellPrice3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(prod3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtyNum3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quanLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(prodCheck3)
                .addContainerGap())
        );

        prod4.setBackground(new java.awt.Color(255, 255, 255));
        prod4.setPreferredSize(new java.awt.Dimension(230, 230));

        prodName4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        prodName4.setText("COSRX Centella Serum");

        pic4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logindemo/cosrx serum.jpg"))); // NOI18N
        pic4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        sellPrice4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sellPrice4.setText("250.00");

        pesoSign4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pesoSign4.setText("₱");

        quanLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        quanLabel4.setText("Quantity:");

        qtyNum4.setText("1");
        qtyNum4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyNum4ActionPerformed(evt);
            }
        });

        prodCheck4.setBackground(new java.awt.Color(255, 255, 255));
        prodCheck4.setText("Add to Cart");

        javax.swing.GroupLayout prod4Layout = new javax.swing.GroupLayout(prod4);
        prod4.setLayout(prod4Layout);
        prod4Layout.setHorizontalGroup(
            prod4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prod4Layout.createSequentialGroup()
                .addGroup(prod4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(prod4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pic4))
                    .addGroup(prod4Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(pesoSign4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sellPrice4))
                    .addGroup(prod4Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(prod4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(prodCheck4)
                            .addGroup(prod4Layout.createSequentialGroup()
                                .addComponent(quanLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(qtyNum4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(prod4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(prodName4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        prod4Layout.setVerticalGroup(
            prod4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, prod4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pic4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodName4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(prod4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesoSign4)
                    .addComponent(sellPrice4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(prod4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtyNum4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quanLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(prodCheck4)
                .addContainerGap())
        );

        prod5.setBackground(new java.awt.Color(255, 255, 255));
        prod5.setPreferredSize(new java.awt.Dimension(230, 230));

        prodName5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        prodName5.setText("Dr. Jart Shake Mask");

        pic5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logindemo/dr.jart mask1.jpg"))); // NOI18N
        pic5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        sellPrice5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sellPrice5.setText("300.00");

        pesoSign5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pesoSign5.setText("₱");

        quanLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        quanLabel5.setText("Quantity:");

        qtyNum5.setText("1");

        prodCheck5.setBackground(new java.awt.Color(255, 255, 255));
        prodCheck5.setText("Add to Cart");

        javax.swing.GroupLayout prod5Layout = new javax.swing.GroupLayout(prod5);
        prod5.setLayout(prod5Layout);
        prod5Layout.setHorizontalGroup(
            prod5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prod5Layout.createSequentialGroup()
                .addGroup(prod5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(prod5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pic5))
                    .addGroup(prod5Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(prodName5))
                    .addGroup(prod5Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(pesoSign5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sellPrice5))
                    .addGroup(prod5Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(prod5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(prodCheck5)
                            .addGroup(prod5Layout.createSequentialGroup()
                                .addComponent(quanLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(qtyNum5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        prod5Layout.setVerticalGroup(
            prod5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, prod5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pic5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodName5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(prod5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesoSign5)
                    .addComponent(sellPrice5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(prod5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtyNum5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quanLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(prodCheck5)
                .addContainerGap())
        );

        prod6.setBackground(new java.awt.Color(255, 255, 255));
        prod6.setPreferredSize(new java.awt.Dimension(230, 230));

        prodName6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        prodName6.setText("Apieu Capsule Mask");

        pic6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logindemo/dr.jart3 mask1.jpg"))); // NOI18N
        pic6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        sellPrice6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sellPrice6.setText("359.00");

        pesoSign6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pesoSign6.setText("₱");

        quanLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        quanLabel6.setText("Quantity:");

        qtyNum6.setText("1");
        qtyNum6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyNum6ActionPerformed(evt);
            }
        });

        prodCheck6.setBackground(new java.awt.Color(255, 255, 255));
        prodCheck6.setText("Add to Cart");

        javax.swing.GroupLayout prod6Layout = new javax.swing.GroupLayout(prod6);
        prod6.setLayout(prod6Layout);
        prod6Layout.setHorizontalGroup(
            prod6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prod6Layout.createSequentialGroup()
                .addGroup(prod6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(prod6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pic6))
                    .addGroup(prod6Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(pesoSign6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sellPrice6))
                    .addGroup(prod6Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(prod6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(prodCheck6)
                            .addGroup(prod6Layout.createSequentialGroup()
                                .addComponent(quanLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(qtyNum6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(prod6Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(prodName6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        prod6Layout.setVerticalGroup(
            prod6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, prod6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pic6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodName6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(prod6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesoSign6)
                    .addComponent(sellPrice6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(prod6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtyNum6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quanLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(prodCheck6)
                .addContainerGap())
        );

        prod7.setBackground(new java.awt.Color(255, 255, 255));
        prod7.setPreferredSize(new java.awt.Dimension(230, 230));

        prodName7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        prodName7.setText("Peripera Velvet Lip Ink");

        pic7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logindemo/peripera-ink-airy-velvet-3903639978050_2000x.jpg"))); // NOI18N
        pic7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        sellPrice7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sellPrice7.setText("400.00");

        pesoSign7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pesoSign7.setText("₱");

        quanLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        quanLabel7.setText("Quantity:");

        qtyNum7.setText("1");
        qtyNum7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyNum7ActionPerformed(evt);
            }
        });

        prodCheck7.setBackground(new java.awt.Color(255, 255, 255));
        prodCheck7.setText("Add to Cart");
        prodCheck7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prodCheck7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout prod7Layout = new javax.swing.GroupLayout(prod7);
        prod7.setLayout(prod7Layout);
        prod7Layout.setHorizontalGroup(
            prod7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prod7Layout.createSequentialGroup()
                .addGroup(prod7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(prod7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pic7))
                    .addGroup(prod7Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(pesoSign7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sellPrice7))
                    .addGroup(prod7Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(prod7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(prodCheck7)
                            .addGroup(prod7Layout.createSequentialGroup()
                                .addComponent(quanLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(qtyNum7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(prod7Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(prodName7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        prod7Layout.setVerticalGroup(
            prod7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, prod7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pic7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodName7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(prod7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesoSign7)
                    .addComponent(sellPrice7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(prod7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtyNum7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quanLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(prodCheck7)
                .addContainerGap())
        );

        prod8.setBackground(new java.awt.Color(255, 255, 255));
        prod8.setPreferredSize(new java.awt.Dimension(230, 230));

        prodName8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        prodName8.setText("Heimish Lip Collection");

        pic8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logindemo/heimish-varnish-velvet-lip-tint-box-4629926772802_2000x.jpg"))); // NOI18N
        pic8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        sellPrice8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sellPrice8.setText("450.00");

        pesoSign8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pesoSign8.setText("₱");

        quanLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        quanLabel8.setText("Quantity:");

        qtyNum8.setText("1");
        qtyNum8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyNum8ActionPerformed(evt);
            }
        });

        prodCheck8.setBackground(new java.awt.Color(255, 255, 255));
        prodCheck8.setText("Add to Cart");

        javax.swing.GroupLayout prod8Layout = new javax.swing.GroupLayout(prod8);
        prod8.setLayout(prod8Layout);
        prod8Layout.setHorizontalGroup(
            prod8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prod8Layout.createSequentialGroup()
                .addGroup(prod8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(prod8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pic8))
                    .addGroup(prod8Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(pesoSign8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sellPrice8))
                    .addGroup(prod8Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(prod8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(prodCheck8)
                            .addGroup(prod8Layout.createSequentialGroup()
                                .addComponent(quanLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(qtyNum8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(prod8Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(prodName8)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        prod8Layout.setVerticalGroup(
            prod8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, prod8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pic8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodName8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(prod8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesoSign8)
                    .addComponent(sellPrice8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(prod8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtyNum8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quanLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(prodCheck8)
                .addContainerGap())
        );

        prod9.setBackground(new java.awt.Color(255, 255, 255));
        prod9.setPreferredSize(new java.awt.Dimension(230, 230));

        prodName9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        prodName9.setText("Peripera Ink Gelato");

        pic9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/logindemo/peripera-ink-the-gelato-4608650936386_2000x.jpg"))); // NOI18N
        pic9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        sellPrice9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        sellPrice9.setText("509.00");

        pesoSign9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pesoSign9.setText("₱");

        quanLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        quanLabel9.setText("Quantity:");

        qtyNum9.setText("1");

        prodCheck9.setBackground(new java.awt.Color(255, 255, 255));
        prodCheck9.setText("Add to Cart");

        javax.swing.GroupLayout prod9Layout = new javax.swing.GroupLayout(prod9);
        prod9.setLayout(prod9Layout);
        prod9Layout.setHorizontalGroup(
            prod9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(prod9Layout.createSequentialGroup()
                .addGroup(prod9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(prod9Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pic9))
                    .addGroup(prod9Layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(pesoSign9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sellPrice9))
                    .addGroup(prod9Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(prod9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(prodCheck9)
                            .addGroup(prod9Layout.createSequentialGroup()
                                .addComponent(quanLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(qtyNum9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(prod9Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(prodName9)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        prod9Layout.setVerticalGroup(
            prod9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, prod9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pic9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prodName9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(prod9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pesoSign9)
                    .addComponent(sellPrice9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(prod9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qtyNum9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quanLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(prodCheck9)
                .addContainerGap())
        );

        javax.swing.GroupLayout mainKaLayout = new javax.swing.GroupLayout(mainKa);
        mainKa.setLayout(mainKaLayout);
        mainKaLayout.setHorizontalGroup(
            mainKaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainKaLayout.createSequentialGroup()
                .addGroup(mainKaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainKaLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(heading))
                    .addGroup(mainKaLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(mainKaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(prod4, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prod1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prod7, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(mainKaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainKaLayout.createSequentialGroup()
                                .addComponent(prod2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(prod3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainKaLayout.createSequentialGroup()
                                .addComponent(prod5, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(prod6, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(mainKaLayout.createSequentialGroup()
                                .addComponent(prod8, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(prod9, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        mainKaLayout.setVerticalGroup(
            mainKaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainKaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(heading)
                .addGap(33, 33, 33)
                .addGroup(mainKaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(prod1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prod2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prod3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainKaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prod4, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prod5, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prod6, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(mainKaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prod7, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prod8, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prod9, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(mainKa);

        checkoutBtn.setBackground(new java.awt.Color(51, 102, 255));
        checkoutBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        checkoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        checkoutBtn.setText("Checkout");
        checkoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutBtnActionPerformed(evt);
            }
        });

        exitBtn.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        exitBtn.setForeground(new java.awt.Color(255, 255, 255));
        exitBtn.setText("X");
        exitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBtnMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("_");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome Back,");

        currUser.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        currUser.setForeground(new java.awt.Color(255, 255, 255));

        cancelBtn.setBackground(new java.awt.Color(255, 0, 51));
        cancelBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Cancel");
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout motherPanelLayout = new javax.swing.GroupLayout(motherPanel);
        motherPanel.setLayout(motherPanelLayout);
        motherPanelLayout.setHorizontalGroup(
            motherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, motherPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(currUser, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitBtn)
                .addContainerGap())
            .addGroup(motherPanelLayout.createSequentialGroup()
                .addGap(294, 294, 294)
                .addComponent(checkoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(292, Short.MAX_VALUE))
        );
        motherPanelLayout.setVerticalGroup(
            motherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(motherPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(motherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8)
                    .addComponent(exitBtn)
                    .addComponent(currUser, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(motherPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(motherPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(motherPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void newTransactions(){
        int transNum=0;
        String nQuery ="INSERT INTO TRANSACTIONS(TRANS_ID, USER_ID, ORDER_DATE) VALUES (TRANS_ID_SEQ.NEXTVAL, ?, ?)";
        PreparedStatement ps;
        Connection nCon = javaconnect.connectdb();
        try{
                ps = nCon.prepareStatement(nQuery);

                ps.setInt(1, UserID);
                ps.setTimestamp(2, date);
                
                    if(ps.executeUpdate() != 0){
                    JOptionPane.showMessageDialog(null, "New Transaction Created. Please wait while we verify your orders");
                    }
                    else{
                    JOptionPane.showMessageDialog(null, "Sorry! Something went wrong.");
                    }
                
                
                nCon.close();
            }
            catch (Exception e){
                JOptionPane.showMessageDialog(null, "Error SQL:"+e);
            }
    }
    
    public int getTransID(){
        int transNum=0;
        PreparedStatement ps;
        Connection sCon = javaconnect.connectdb();
        try{
                ps = sCon.prepareStatement("SELECT MAX(TRANS_ID) FROM TRANSACTIONS");
                
                ResultSet rs = ps.executeQuery();
                if (rs.next()) {
                    transNum = rs.getInt(1);
                }
        }
        catch(Exception e){
            System.out.println("getTransError: " + e);
        }
        return transNum;
    }
    
    public void newOrder(JTextField qty, JLabel price, int trans, JLabel name, String item_type){
        int quantity = Integer.parseInt(qty.getText());
        float prices = (int) Float.parseFloat(price.getText()); 
        try{
            con = javaconnect.connectdb();
                stmt = con.createStatement();
                Query = "INSERT INTO ORDER_ITEMS(ORDER_ITEM_ID, TRANS_ID, ITEM_NAME, ITEM_TYPE, PRICE, QTY, USER_ID) values (ORDER_ID_SEQ.NEXTVAL," + trans 
                        + ",'" + name.getText() + "','" + item_type + "'," + prices + "," + quantity + "," + UserID + ")";
                stmt.executeUpdate(Query);
                System.out.println("Order Created");
        }
        catch(Exception e){
            System.out.println("newOrder Error: " + e);
        }
                
    }
    
    public boolean verifData(){
        if(!(prodCheck1.isSelected()) && !(prodCheck2.isSelected()) &&!(prodCheck3.isSelected()) &&
               !(prodCheck4.isSelected()) && !(prodCheck5.isSelected()) &&!(prodCheck6.isSelected()) &&
               !(prodCheck7.isSelected()) && !(prodCheck8.isSelected()) &&!(prodCheck9.isSelected())){
                JOptionPane.showMessageDialog(null, "Checkout Failed! No item was added to the cart.");
                return false;
            }else{
                return true;
            
        }
//        if((prodCheck1.isSelected()) || (prodCheck2.isSelected()) || (prodCheck3.isSelected()) ||
//                (prodCheck4.isSelected()) || (prodCheck5.isSelected()) || (prodCheck6.isSelected()) ||
//                (prodCheck7.isSelected()) || (prodCheck8.isSelected()) || (prodCheck9.isSelected()))
        
    }
    
    private void checkoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutBtnActionPerformed
        // TODO add your handling code here:
        
                
        try{
            if(verifData()){
                newTransactions();
                transID=getTransID();
                
                if(prodCheck1.isSelected()){
                newOrder(qtyNum1, sellPrice1, transID, prodName1, "Face Mask");
                }
                if(prodCheck2.isSelected()){
                    newOrder(qtyNum2, sellPrice2, transID, prodName2, "Face Mask");
                }
                if(prodCheck3.isSelected()){
                    newOrder(qtyNum3, sellPrice3, transID, prodName3, "Clay Mask");
                }
                if(prodCheck4.isSelected()){
                    newOrder(qtyNum4, sellPrice4, transID, prodName4, "Serum");
                }
                if(prodCheck5.isSelected()){
                    newOrder(qtyNum5, sellPrice5, transID, prodName5, "Clay Mask");
                }
                if(prodCheck6.isSelected()){
                    newOrder(qtyNum6, sellPrice6, transID, prodName6, "Face Mask");
                }
                if(prodCheck7.isSelected()){
                    newOrder(qtyNum7, sellPrice7, transID, prodName7, "Lip Tint");
                }
                if(prodCheck8.isSelected()){
                    newOrder(qtyNum8, sellPrice8, transID, prodName8, "Lip Tint");
                }
                if(prodCheck9.isSelected()){
                    newOrder(qtyNum9, sellPrice9, transID, prodName9, "Lip Tint");
                }
                
                JOptionPane.showMessageDialog(null, "Checkout Successfull! Please wait for your orders.");
               stmt.close();
               con.close();
               new CheckoutPage(UserID, transID).setVisible(true);
               this.dispose();
            }
        }
        catch (SQLException e){JOptionPane.showMessageDialog(null, "Error SQL:"+e);}
        
        
    }//GEN-LAST:event_checkoutBtnActionPerformed

    private void qtyNum4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyNum4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyNum4ActionPerformed

    private void qtyNum6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyNum6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyNum6ActionPerformed

    private void qtyNum7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyNum7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyNum7ActionPerformed

    private void qtyNum8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyNum8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyNum8ActionPerformed

    private void qtyNum2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyNum2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyNum2ActionPerformed

    private void prodCheck7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodCheck7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodCheck7ActionPerformed

    private void prodCheck1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prodCheck1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prodCheck1ActionPerformed

    private void exitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBtnMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitBtnMouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserCatalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserCatalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserCatalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserCatalog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserCatalog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton checkoutBtn;
    private javax.swing.JLabel currUser;
    private javax.swing.JLabel exitBtn;
    private javax.swing.JLabel heading;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel mainKa;
    private javax.swing.JPanel motherPanel;
    private javax.swing.JLabel pesoSign1;
    private javax.swing.JLabel pesoSign2;
    private javax.swing.JLabel pesoSign3;
    private javax.swing.JLabel pesoSign4;
    private javax.swing.JLabel pesoSign5;
    private javax.swing.JLabel pesoSign6;
    private javax.swing.JLabel pesoSign7;
    private javax.swing.JLabel pesoSign8;
    private javax.swing.JLabel pesoSign9;
    private javax.swing.JLabel pic1;
    private javax.swing.JLabel pic2;
    private javax.swing.JLabel pic3;
    private javax.swing.JLabel pic4;
    private javax.swing.JLabel pic5;
    private javax.swing.JLabel pic6;
    private javax.swing.JLabel pic7;
    private javax.swing.JLabel pic8;
    private javax.swing.JLabel pic9;
    private javax.swing.JPanel prod1;
    private javax.swing.JPanel prod2;
    private javax.swing.JPanel prod3;
    private javax.swing.JPanel prod4;
    private javax.swing.JPanel prod5;
    private javax.swing.JPanel prod6;
    private javax.swing.JPanel prod7;
    private javax.swing.JPanel prod8;
    private javax.swing.JPanel prod9;
    private javax.swing.JCheckBox prodCheck1;
    private javax.swing.JCheckBox prodCheck2;
    private javax.swing.JCheckBox prodCheck3;
    private javax.swing.JCheckBox prodCheck4;
    private javax.swing.JCheckBox prodCheck5;
    private javax.swing.JCheckBox prodCheck6;
    private javax.swing.JCheckBox prodCheck7;
    private javax.swing.JCheckBox prodCheck8;
    private javax.swing.JCheckBox prodCheck9;
    private javax.swing.JLabel prodName1;
    private javax.swing.JLabel prodName2;
    private javax.swing.JLabel prodName3;
    private javax.swing.JLabel prodName4;
    private javax.swing.JLabel prodName5;
    private javax.swing.JLabel prodName6;
    private javax.swing.JLabel prodName7;
    private javax.swing.JLabel prodName8;
    private javax.swing.JLabel prodName9;
    private javax.swing.JTextField qtyNum1;
    private javax.swing.JTextField qtyNum2;
    private javax.swing.JTextField qtyNum3;
    private javax.swing.JTextField qtyNum4;
    private javax.swing.JTextField qtyNum5;
    private javax.swing.JTextField qtyNum6;
    private javax.swing.JTextField qtyNum7;
    private javax.swing.JTextField qtyNum8;
    private javax.swing.JTextField qtyNum9;
    private javax.swing.JLabel quanLabel1;
    private javax.swing.JLabel quanLabel2;
    private javax.swing.JLabel quanLabel3;
    private javax.swing.JLabel quanLabel4;
    private javax.swing.JLabel quanLabel5;
    private javax.swing.JLabel quanLabel6;
    private javax.swing.JLabel quanLabel7;
    private javax.swing.JLabel quanLabel8;
    private javax.swing.JLabel quanLabel9;
    private javax.swing.JLabel sellPrice1;
    private javax.swing.JLabel sellPrice2;
    private javax.swing.JLabel sellPrice3;
    private javax.swing.JLabel sellPrice4;
    private javax.swing.JLabel sellPrice5;
    private javax.swing.JLabel sellPrice6;
    private javax.swing.JLabel sellPrice7;
    private javax.swing.JLabel sellPrice8;
    private javax.swing.JLabel sellPrice9;
    // End of variables declaration//GEN-END:variables
}
